"""Storage migration regressions; integration cases use disposable PG schemas.

Set YEARN_TEST_POSTGRES_URL to exercise real Postgres. No test uses public tables.
"""
from contextlib import closing
import json
import os
import uuid

import psycopg
from psycopg import sql
import pytest

from yearn_data.analysis import create_analysis_run, write_output
from yearn_data.coverage import Scope, commit_range, missing_ranges
from yearn_data.exports import export_analysis
from yearn_data.postgres import parameters, schema_statements
from yearn_data.postgres_migration import migration_plan, migrate_sqlite
from yearn_data.storage import connect, init_db, database_reference, table_exists


def test_parameter_conversion_preserves_quoted_question_marks_and_modulo():
    statement = "SELECT ? AS value, '?' AS literal, 7%3 AS rest WHERE ? LIKE '%?%' -- ? comment\n"
    assert parameters(statement) == "SELECT %s AS value, '?' AS literal, 7%%3 AS rest WHERE %s LIKE '%%?%%' -- ? comment\n"


def test_schema_translation_preserves_default_text_and_forward_references():
    statements = schema_statements("""
        CREATE TABLE child(id INTEGER, parent INTEGER REFERENCES parent(id), value REAL, note TEXT DEFAULT 'INTEGER; REAL');
        CREATE TABLE parent(id INTEGER PRIMARY KEY AUTOINCREMENT);
    """)
    assert 'CREATE TABLE parent' in statements[0]
    assert 'GENERATED BY DEFAULT AS IDENTITY' in statements[0]
    assert 'DOUBLE PRECISION' in statements[1]
    assert "DEFAULT 'INTEGER; REAL'" in statements[1]


def test_publication_rejects_embedded_database_credentials():
    with pytest.raises(ValueError, match='logical database name'):
        database_reference('postgresql://user:secret@localhost/db')
    assert database_reference('neon') == 'neon'


@pytest.fixture
def pg(monkeypatch):
    url = os.environ.get('YEARN_TEST_POSTGRES_URL')
    if not url:
        pytest.skip('YEARN_TEST_POSTGRES_URL not configured')
    name = 'yearn_test_' + uuid.uuid4().hex
    with psycopg.connect(url, autocommit=True) as admin:
        admin.execute(sql.SQL('CREATE SCHEMA {}').format(sql.Identifier(name)))
        monkeypatch.setenv('NEON_DB_URL', url)
        monkeypatch.setenv('YEARN_DATA_DB_SCHEMA', name)
        try:
            with closing(connect('neon')) as conn:
                yield conn, name
        finally:
            admin.execute(sql.SQL('DROP SCHEMA {} CASCADE').format(sql.Identifier(name)))


def test_real_postgres_atomic_coverage_and_readonly(pg):
    conn, _ = pg
    init_db(conn)
    scope = Scope(1, 'vault', 'reports')
    # A read must not prevent the writer from starting a clean atomic range.
    assert list(missing_ranges(conn, scope, 0, 9, 10)) == [(0,9)]
    def fail(writer):
        writer.execute("INSERT INTO block_timestamps VALUES (1,1,1)")
        raise ValueError('injected interruption')
    with pytest.raises(ValueError, match='injected'):
        commit_range(conn,scope,0,9,source='rpc',end_hash='hash',run_id=None,write=fail)
    assert conn.execute('SELECT count(*) FROM block_timestamps').fetchone()[0] == 0
    assert list(missing_ranges(conn, scope, 0, 9, 10)) == [(0,9)]
    commit_range(conn,scope,0,9,source='rpc',end_hash='hash',run_id=None,
                 write=lambda writer: writer.execute('INSERT INTO block_timestamps VALUES (1,1,1)').rowcount)
    assert list(missing_ranges(conn, scope, 0, 9, 10)) == []
    with closing(connect('neon', readonly=True)) as reader:
        assert reader.execute('SELECT count(*) FROM block_timestamps').fetchone()[0] == 1
        with pytest.raises(psycopg.errors.ReadOnlySqlTransaction):
            reader.execute('DELETE FROM block_timestamps')


def sqlite_history(path):
    conn = connect(path)
    init_db(conn)
    conn.execute("INSERT INTO analysis_runs VALUES (13,'lifetime-yield',1,2,'complete','{}')")
    conn.execute("INSERT INTO analysis_runs VALUES (99,'deleted',1,2,'complete','{}')")
    conn.execute('DELETE FROM analysis_runs WHERE id=99')
    for rowid, value in ((12, 'last'),(-5, 'first')):
        raw = json.dumps({'value':value,'raw':str(2**255),'usd':'123.4567890123456789','missing':None,'zero':'0'})
        conn.execute('INSERT INTO analysis_outputs(rowid,run_id,name,row_json) VALUES (?,13,?,?)',(rowid,'reports',raw))
    conn.execute("INSERT INTO tvl_runs VALUES (401,1,2,'complete','{}')")
    raw = json.dumps({'quantity':str(2**255),'tvl_usd':None})
    conn.execute('INSERT INTO tvl_snapshots VALUES (401,1,?,?,1,?)', ('vault',123,raw))
    conn.execute('INSERT INTO tvl_prices VALUES (1,?,123,1,?,?,?,?)',
                 ('asset','yearn-prices',1.23456789012345,'ok','{}'))
    conn.commit()
    return conn


def test_real_migration_preserves_order_precision_nulls_and_reserved_ids(pg,tmp_path):
    conn, _ = pg
    path = tmp_path/'history.sqlite'
    with closing(sqlite_history(path)) as source:
        plan = migration_plan(path)
        assert not table_exists(conn,'analysis_runs')
        assert plan['tables']['analysis_outputs'] == 2
        result = migrate_sqlite(path,batch_size=1)
        assert result['analysis_fingerprints_preserved']
        rows = list(conn.execute('SELECT rowid,row_json FROM analysis_outputs ORDER BY rowid'))
        assert [r[0] for r in rows] == [-5,12]
        assert [tuple(r) for r in rows] == [tuple(r) for r in source.execute('SELECT rowid,row_json FROM analysis_outputs ORDER BY rowid')]
        assert conn.execute('SELECT price_usd FROM tvl_prices').fetchone()[0] == 1.23456789012345
        assert conn.execute('SELECT data_json FROM tvl_snapshots').fetchone()[0] == source.execute('SELECT data_json FROM tvl_snapshots').fetchone()[0]
        assert create_analysis_run(conn,'next') == 100
        write_output(conn,13,'reports',{'value':'new'})
        conn.commit()
        assert conn.execute('SELECT MAX(rowid) FROM analysis_outputs').fetchone()[0] == 13
        exported = export_analysis(conn,'lifetime-yield',tmp_path/'exports',run_id=13)
        assert 'first' in exported[0].read_text().splitlines()[1]
        with pytest.raises(ValueError,match='must be empty'):
            migrate_sqlite(path)


def test_real_migration_failure_leaves_target_empty(pg,tmp_path):
    conn, _ = pg
    path = tmp_path/'history.sqlite'
    sqlite_history(path).close()
    def interrupted(message):
        if message.startswith('copied analysis_outputs'):
            raise RuntimeError('injected copy interruption')
    with pytest.raises(RuntimeError,match='interruption'):
        migrate_sqlite(path,progress=interrupted)
    assert not table_exists(conn,'analysis_runs')
    assert migrate_sqlite(path)['status'] == 'complete'


@pytest.mark.parametrize('case', [
    'test_accumulated_history_repair_and_failed_retry_preserve_known_data',
    'test_current_bridge_policy_not_retroactive_and_chain_filter_consistent',
    'test_rejected_provider_quote_is_not_served_or_used_as_reference',
])
def test_existing_tvl_api_regressions_on_postgres(pg,tmp_path,monkeypatch,case):
    import inspect
    import test_tvl_api as cases
    conn, _ = pg
    init_db(conn)
    for address,active in ((cases.PARENT,1),(cases.CHILD,1),(cases.BRIDGE,0)):
        conn.execute("INSERT INTO tvl_vaults(chain_id,version,address,active,updated_at) VALUES (1,'v3',?,?,1)",(address,active))
    conn.execute("INSERT INTO tvl_vaults(chain_id,version,address,active,updated_at) VALUES (10,'v3',?,1,1)",(cases.CHILD,))
    conn.commit()
    fn = getattr(cases,case)
    args = {'source':(conn,'neon',tmp_path/'tvl')}
    if 'monkeypatch' in inspect.signature(fn).parameters:
        args['monkeypatch'] = monkeypatch
    fn(**args)


def test_existing_fee_pairing_contract_on_postgres(pg,tmp_path):
    from test_pairing import snapshots
    from yearn_data.pairing import PairingDataset, select_pairing, PairingStore
    conn, _ = pg
    init_db(conn)
    runs = snapshots(conn)
    dataset = PairingDataset('neon',*runs)
    summary = dataset.view('summary')
    assert summary['totalFeesPaidUsd'] == '22'
    assert summary['netLifetimeEarningsUsd'] == '135'
    selected = select_pairing('neon',*runs,tmp_path/'fees')
    assert selected['database'] == 'neon'
    assert 'postgresql://' not in json.dumps(selected)
    assert PairingStore(tmp_path/'fees').get().id == dataset.id


@pytest.mark.parametrize('case', [
    'test_factory_uses_actual_family_events_and_resumes',
    'test_fresh_catalog_collect_and_export_without_migration',
])
def test_existing_discovery_and_collection_on_postgres(pg,tmp_path,monkeypatch,case):
    import inspect
    import test_tvl_discovery as cases
    conn, _ = pg
    init_db(conn)
    fn = getattr(cases,case)
    available = {'db':conn,'tmp_path':tmp_path,'monkeypatch':monkeypatch}
    fn(**{name:available[name] for name in inspect.signature(fn).parameters})


@pytest.mark.parametrize('pipeline',[False,True])
def test_existing_lifetime_yield_analysis_on_postgres(pg,tmp_path,monkeypatch,pipeline):
    import test_analysis as cases
    from yearn_data.storage import seed_chains
    from yearn_data.config import CHAINS
    conn, _ = pg
    init_db(conn)
    seed_chains(conn,CHAINS)
    # Reuse the financial regression's data and expectations with a PG writer.
    monkeypatch.setattr(cases,'connect',lambda _:conn)
    from contextlib import nullcontext
    with conn.raw.pipeline() if pipeline else nullcontext():
        cases.test_lifetime_yield_uses_net_gain_minus_loss(tmp_path)


def test_fee_price_retry_replaces_missing_with_exact_price(pg,monkeypatch):
    from yearn_data.fee_valuation import save_price
    conn, _ = pg
    init_db(conn)
    monkeypatch.setattr('yearn_data.fee_valuation.endpoint_identity',lambda:'test-endpoint')
    target = (1,'asset',1704067199)
    save_price(conn,target,(None,'missing',{}))
    evidence = {'provider':'yearn-prices','normalized_timestamp':target[2]}
    save_price(conn,target,('1.234567890123456789','ok',evidence))
    conn.commit()
    rows = conn.execute('SELECT price_usd,status,evidence_json FROM fee_daily_prices').fetchall()
    assert len(rows) == 1
    assert rows[0]['price_usd'] == '1.234567890123456789'
    assert rows[0]['status'] == 'ok'
    assert json.loads(rows[0]['evidence_json']) == evidence


def test_prepared_chart_rows_and_totals_on_real_postgres(pg,tmp_path):
    from test_tvl_api import run,DAY,PARENT,CHILD
    from yearn_data.tvl_api import TvlStore,TvlDataset
    from yearn_data.tvl_history_cache import prepare
    conn,_=pg
    init_db(conn)
    run(conn,1,DAY,[(PARENT,'100'),(CHILD,'100')],[(CHILD,'50')])
    run(conn,2,DAY+86400,[(PARENT,'200'),(CHILD,'200')],[(CHILD,'100')])
    original=TvlStore('neon',tmp_path/'tvl').get()
    expected=original.history(interval='daily')
    constant=original.history(group='vault',interval='daily',constant=True)
    prepare(original)
    cached=TvlDataset(original.manifest)
    assert cached.history(interval='daily')==expected
    assert cached.history(group='vault',interval='daily',constant=True)==constant
    assert cached.history(interval='daily',start=DAY+100*86400)['chart']==[]
