"""Postgres transport for the toolkit's small, shared SQL interface.

Queries keep qmark parameters and SQLite Row access. SQL values always remain
driver parameters; this module translates placeholders, not interpolated values.
"""
from __future__ import annotations

import re
import uuid

import psycopg
from psycopg.pq import TransactionStatus


QUOTED = re.compile(r"('(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*(?:\n|$)|/\*[\s\S]*?\*/)")


def outside_quotes(statement, transform):
    return ''.join(part if index % 2 else transform(part)
                   for index, part in enumerate(QUOTED.split(statement)))


def parameters(statement):
    # libpq's parameter syntax also requires escaping literal percent signs,
    # including LIKE patterns and the modulo operator used in TVL ranking.
    statement = statement.replace('%', '%%')
    return outside_quotes(statement, lambda part: part.replace('?', '%s'))


def query(statement):
    statement = re.sub(
        r"json_extract\(\s*([\w.]+)\s*,\s*'\$\.([\w.]+)'\s*\)",
        lambda match: "(CAST(" + match[1] + " AS jsonb) #>> '{" + match[2].replace('.', ',') + "}')",
        statement, flags=re.I,
    )
    return outside_quotes(statement, lambda part: re.sub(r'\bREAL\b', 'DOUBLE PRECISION', part, flags=re.I))


def schema_statement(statement):
    def types(part):
        part = re.sub(r'\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b',
                      'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY', part, flags=re.I)
        part = re.sub(r'\bINTEGER\b', 'BIGINT', part, flags=re.I)
        return re.sub(r'\bREAL\b', 'DOUBLE PRECISION', part, flags=re.I)
    result = outside_quotes(statement, types)
    if re.match(r'\s*CREATE TABLE (?:IF NOT EXISTS )?analysis_outputs\s*\(', result, re.I):
        result = re.sub(r'(analysis_outputs\s*\()',
                        r'\1\n    rowid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,', result, flags=re.I)
    return result


def schema_statements(script):
    """Order referenced tables before their dependants (SQLite permits either)."""
    import sqlite3
    statements, pending = [], ''
    for char in script:
        pending += char
        if char == ';' and sqlite3.complete_statement(pending):
            statements.append(pending.strip().rstrip(';'))
            pending = ''
    if pending.strip():
        statements.append(pending.strip())
    tables, others = {}, []
    for statement in statements:
        if statement.upper().startswith('PRAGMA '):
            continue
        match = re.match(r'CREATE TABLE (?:IF NOT EXISTS )?["`]?([\w]+)', statement, re.I)
        if match:
            tables[match[1]] = statement
        else:
            others.append(statement)
    ordered = []
    while tables:
        ready = [name for name, statement in tables.items()
                 if not (set(re.findall(r'REFERENCES\s+["`]?([\w]+)', statement, re.I)) & tables.keys())]
        if not ready:
            raise ValueError('cyclic schema dependencies require an explicit migration')
        ordered.extend(tables.pop(name) for name in ready)
    return [schema_statement(statement) for statement in ordered + others]


def create_indexes(conn):
    """Support selected analyses and common dated reads across many TVL runs."""
    for statement in (
        'CREATE INDEX IF NOT EXISTS analysis_outputs_run_name_rowid_idx ON analysis_outputs(run_id,name,rowid)',
        'CREATE INDEX IF NOT EXISTS tvl_snapshots_timestamp_run_idx ON tvl_snapshots(timestamp,run_id)',
        'CREATE INDEX IF NOT EXISTS tvl_positions_timestamp_run_idx ON tvl_positions(timestamp,run_id)',
    ):
        conn.raw.execute(statement)


class Row:
    """Support both row['column']/dict(row) and tuple unpacking, as sqlite3.Row does."""
    def __init__(self, names, values):
        self.names, self.values = names, values

    def keys(self):
        return self.names

    def __getitem__(self, key):
        if isinstance(key, str):
            try:
                key = self.names.index(key)
            except ValueError:
                raise IndexError('no such column') from None
        return self.values[key]

    def __iter__(self):
        return iter(self.values)

    def __len__(self):
        return len(self.values)


def row_factory(cursor):
    names = tuple(column.name for column in (cursor.description or ()))
    return lambda values: Row(names, values)


class Connection:
    def __init__(self, url, *, readonly=False, schema='public', direct=False):
        from psycopg.conninfo import conninfo_to_dict
        params = conninfo_to_dict(url)
        params.setdefault('sslmode', 'require')
        params['connect_timeout'] = '15'
        if direct and params.get('host', '').endswith('.neon.tech'):
            params['host'] = params['host'].replace('-pooler.', '.')
        self.raw = psycopg.connect(**params, autocommit=True, row_factory=row_factory, prepare_threshold=None)
        try:
            self.raw.execute(psycopg.sql.SQL('SET search_path TO {}').format(psycopg.sql.Identifier(schema)))
            if readonly:
                self.raw.execute('SET default_transaction_read_only = on')
        except Exception:
            self.raw.close()
            raise
        self.readonly = readonly

    @property
    def in_transaction(self):
        return self.raw.info.transaction_status != TransactionStatus.IDLE

    def _begin_write(self, statement):
        # Match SQLite: reads outside a context do not leave idle transactions.
        if not self.in_transaction and re.match(r'\s*(INSERT|UPDATE|DELETE)\b', statement, re.I):
            self.raw.execute('BEGIN')

    def execute(self, statement, params=()):
        self._begin_write(statement)
        if re.match(r'\s*(CREATE|ALTER)\b', statement, re.I):
            statement = schema_statement(statement)
        return self.raw.execute(parameters(query(statement)), params)

    def executemany(self, statement, rows):
        self._begin_write(statement)
        cursor = self.raw.cursor()
        cursor.executemany(parameters(query(statement)), rows)
        return cursor

    def stream(self, statement, params=()):
        """Bounded reads inside the caller's transaction."""
        with self.raw.cursor(name='yearn_'+uuid.uuid4().hex) as cursor:
            cursor.itersize=2000
            cursor.execute(parameters(query(statement)),params)
            yield from cursor

    def executescript(self, script):
        for statement in schema_statements(script):
            self.raw.execute(statement)

    def commit(self):
        self.raw.commit()

    def rollback(self):
        self.raw.rollback()

    def close(self):
        self.raw.close()

    def __enter__(self):
        if not self.in_transaction:
            self.raw.execute('BEGIN ISOLATION LEVEL REPEATABLE READ' if self.readonly else 'BEGIN')
        return self

    def __exit__(self, kind, value, traceback):
        self.rollback() if kind else self.commit()
